server:
  port: 8081
  servlet:
    context-path: '/mi-myinvoice-back/'

spring:
  application:
    name: mi-myinvoice-back
  data:
    web:
      pageable:
        page-parameter: 0
        default-page-size: 50
  datasource:
    url: jdbc:postgresql://localhost:5432/myinvoicedb
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      jdbc:
        lob.non-contextual-creation: true
    properties:
      originPrefix: MI
    open-in-view: false
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    br.com.isertech.myinvoice-back: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

mi:
  serviceRegistry:
    username: serviceregistry
    password: vento123
  auth:
    jwtSecret: test
    jwtExpirationMs: 14400000

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: 'http://${mi.serviceRegistry.username}:${mi.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

#clients:
#  user-client:
#    name: 'user-client'
#    url: 'localhost:8080/wt-user-service'

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 100
        waitDurationInOpenState: 60s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        max-attempts: 3
        waitDuration: 5s